AT
 D INIT^TTRNSI
 D INIT^TT
 N BA
 S BA("TOP")=10,BA("LEFT")=10,BA("RIGHT")=30,BA("BOTTOM")=16
 S BA("TITLE")="TEST ALERT"
 S BA("LINES",1)=""
 S BA("LINES",2)="Test alert box."
 D ALERTBOX^TTUI(.BA)
 R *TMP
 Q