TT
 ;S $ETRAP="G ERROR^TT"
 S $ZDATEFORM=2
 D INIT
 N RESP
REAUTH
 I $G(TTAUTHED)'=1 D FAUTH^TTAUTH
 G:TTAUTHED=0 REAUTH
 D PRIMARY

PRIMARY
 N MA
 S MA("TITLE")="MAIN MENU"
 S MA("ITEMS","ADMINISTRATION")="D ADMIN^TT"
 S MA("ITEMS","FINANCIALS")="D FINANCE^TT"
 S MA("ITEMS","CUSTOMERS")="D ^TTCUST"
 S MA("ITEMS","TIME COLLECTION")="D TIMECOLL^TT"
 S MA("ITEMS","QUIT IGLS")="D QUITIGLS^TT"
 D GO^TTMENU(.MA)
 G PRIMARY
 Q

TIMECOLL
 N MA
TCTOP
 S MA("TITLE")="TIME COLLECTION"
 S MA("ITEMS","START LOG")="D START^TTLOG"
 S MA("ITEMS","STOP LOG")="D STOP^TTLOG"
 S MA("ITEMS","LIST LOGS")="D LIST^TTLOG"
 S MA("ITEMS","NEW ENTRY")="D CREATE^TTENTRY"
 S MA("ITEMS","QUIT TO MAIN MENU")="D ^TT"
 D GO^TTMENU(.MA)
 G TCTOP
 Q

ADMIN
 N MA
ADMINTOP
 S MA("TITLE")="ADMINISTRATION"
 S MA("ITEMS","USER RIGHTS MANAGEMENT")="D ^TTAUTH"
 S MA("ITEMS","SYSTEM SETUP")="D ^TTSETUP"
 S MA("ITEMS","QUIT TO MAIN MENU")="D ^TT"
 D GO^TTMENU(.MA)
 G ADMINTOP
 Q

FINANCE
 N MA
FINANCETOP
 S MA("TITLE")="FINANCIALS"
 S MA("ITEMS","INVOICING")="D INVOICING^TT"
 S MA("ITEMS","GENERAL LEDGER SYSTEM")="D ^TTACCOUNT"
 S MA("ITEMS","QUIT TO MAIN MENU")="D ^TT"
 D GO^TTMENU(.MA)
 G FINANCETOP
 Q

INVOICING
 N MA
INVOICETOP
 S MA("TITLE")="INVOICING"
 S MA("ITEMS","RUN INVOICES")="D ^TTINVOICE"
 S MA("ITEMS","PREVIEW INVOICE")="D PREVIEW^TTINVOICE"
 S MA("ITEMS","RECEIVE PAYMENT")="D RECEIVE^TTPAYMENT"
 S MA("ITEMS","CUSTOMER HISTORY")="D SHOW^TTCUST"
 S MA("ITEMS","QUIT TO MAIN MENU")="D ^TT"
 D GO^TTMENU(.MA)
 G INVOICETOP
 Q 

QUITIGLS
 D ESC^TTRNSI("c")
 HALT

INIT
 U $P:(CONVERT:NOWRAP)
 D INIT^TTRNSI
 D NOSCROLLREGION^TTRNSI
 D SETCOLOR^TTRNSI("WHITE","BLACK")
 D CLEAR^TTRNSI
 D SCROLLREGION^TTRNSI(3,22)
 D LOCATE^TTRNSI(1,1)
 D SETATTR^TTRNSI("BRIGHT")
 D SETCOLOR^TTRNSI("CYAN","BLACK")
 W "IGLS"
 D SETATTR^TTRNSI("RESET")
 D SETCOLOR^TTRNSI("GREEN","BLACK")
 D LOCATE^TTRNSI(1,69)
 W $G(TTUSER,"NO USER")
 D SETCOLOR^TTRNSI("GREEN","BLACK")
 D LOCATE^TTRNSI(2,1)
 F I=1:1:80 D LOCATE^TTRNSI(2,I) W BOX("H")
 D LOCATE^TTRNSI(23,1)
 F I=1:1:80 D LOCATE^TTRNSI(23,I) W BOX("H")
 D LOCATE^TTRNSI(3,1)
 Q

ERROR
 D ESC^TTRNSI("c")
 ZWR
 BREAK
 Q

RESET
 D ESC^TTRNSI("c")
 Q