TT
 S $ETRAP="G ERROR^TT"
 S $ZDATEFORM=2
 D INIT
 N RESP
REAUTH
 I $G(TTAUTHED)'=1 D FAUTH^TTAUTH
 G:TTAUTHED=0 REAUTH
 D PRIMARY

PRIMARY
 N MA
 S MA("TITLE")="MAIN MENU"
 S MA("ITEMS","ADMINISTRATION")="D ADMIN^TT"
 S MA("ITEMS","FINANCIALS")="D FINANCE^TT"
 S MA("ITEMS","CUSTOMERS")="D ^TTCUST"
 S MA("ITEMS","TIME COLLECTION")="D TIMECOLL^TT"
 S MA("ITEMS","ADMINISTRATION","KEY")="XKADM:V"
 S MA("ITEMS","FINANCIALS","KEY")="XKGLS:V"
 S MA("ITEMS","CUSTOMERS","KEY")="XKCST:V"
 S MA("ITEMS","TIME COLLECTION","KEY")="XKTC:V"
 S MA("ITEMS","IMPORT/EXPORT")="D ^TTIMPORT"
 S MA("ITEMS","IMPORT/EXPORT","KEY")="XKGLS:M"
 S MA("ITEMS","QUIT IGLS")="D QUITIGLS^TT"
 D GO^TTMENU(.MA)
 G PRIMARY
 Q

TIMECOLL
 N MA
TCTOP
 S MA("TITLE")="TIME COLLECTION"
 S MA("ITEMS","START LOG")="D START^TTLOG"
 S MA("ITEMS","STOP LOG")="D STOP^TTLOG"
 S MA("ITEMS","CANCEL LOG")="D CANCEL^TTLOG"
 S MA("ITEMS","CANCEL LOG","KEY")="XKTC:M"
 S MA("ITEMS","LIST LOGS")="D LIST^TTLOG"
 S MA("ITEMS","NEW ENTRY")="D CREATE^TTENTRY"
 S MA("ITEMS","START LOG","KEY")="XKTC:M"
 S MA("ITEMS","STOP LOG","KEY")="XKTC:M"
 S MA("ITEMS","LIST LOGS","KEY")="XKTC:V"
 S MA("ITEMS","NEW ENTRY","KEY")="XKTC:M"
 S MA("ITEMS","QUIT TO MAIN MENU")="D ^TT"
 D GO^TTMENU(.MA)
 G TCTOP
 Q

ADMIN
 N MA
ADMINTOP
 S MA("TITLE")="ADMINISTRATION"
 S MA("ITEMS","USER RIGHTS MANAGEMENT")="D ^TTAUTH"
 S MA("ITEMS","SYSTEM SETUP")="D ^TTSETUP"
 S MA("ITEMS","USER RIGHTS MANAGEMENT","KEY")="XKADM:V"
 S MA("ITEMS","SYSTEM SETUP","KEY")="XKADM:M"
 S MA("ITEMS","QUIT TO MAIN MENU")="D ^TT"
 D GO^TTMENU(.MA)
 G ADMINTOP
 Q

FINANCE
 N MA
FINANCETOP
 S MA("TITLE")="FINANCIALS"
 S MA("ITEMS","INVOICING")="D INVOICING^TT"
 S MA("ITEMS","GENERAL LEDGER SYSTEM")="D ^TTACCOUNT"
 S MA("ITEMS","INVOICING","KEY")="XKINV:V"
 S MA("ITEMS","GENERAL LEDGER SYSTEM","KEY")="XKGLS:V"
 S MA("ITEMS","QUIT TO MAIN MENU")="D ^TT"
 D GO^TTMENU(.MA)
 G FINANCETOP
 Q

INVOICING
 N MA
INVOICETOP
 S MA("TITLE")="INVOICING"
 S MA("ITEMS","RUN INVOICES")="D ^TTINVOICE"
 S MA("ITEMS","PREVIEW INVOICE")="D PREVIEW^TTINVOICE"
 S MA("ITEMS","RECEIVE PAYMENT")="D RECEIVE^TTPAYMENT"
 S MA("ITEMS","CUSTOMER HISTORY")="D SHOW^TTCUST"
 S MA("ITEMS","RUN INVOICES","KEY")="XKINV:M"
 S MA("ITEMS","PREVIEW INVOICE","KEY")="XKINV:V"
 S MA("ITEMS","RECEIVE PAYMENT","KEY")="XKINV:M"
 S MA("ITEMS","CUSTOMER HISTORY","KEY")="XKINV:V"
 S MA("ITEMS","QUIT TO MAIN MENU")="D ^TT"
 D GO^TTMENU(.MA)
 G INVOICETOP
 Q 

QUITIGLS
 D RESET^TTRNSI
 HALT

HELP
 I $G(TTHELP)'="" X TTHELP
 Q

INIT
 U $P:(CONVERT:NOWRAP)
 D INIT^TTRNSI
 D ADDACCEL^%TERMIO("KEY_F9","D QUITIGLS^TT","QUIT IGLS")
 D ADDACCEL^%TERMIO("KEY_F1","D HELP^TT","HELP")
 D NOSCROLLREGION^TTRNSI
 D SETCOLOR^TTRNSI("WHITE","BLACK")
 D CLEAR^TTRNSI
 D SCROLLREGION^TTRNSI(3,22)
 D SETATTR^TTRNSI("RESET")
 D LOCATE^TTRNSI(1,1)
 D SETATTR^TTRNSI("BRIGHT")
 D SETCOLOR^TTRNSI("CYAN","BLACK")
 W "IGLS"
 D SETATTR^TTRNSI("RESET")
 D SETCOLOR^TTRNSI("GREEN","BLACK")
 D LOCATE^TTRNSI(1,69)
 W $G(TTUSER,"NO USER")
 D SETCOLOR^TTRNSI("GREEN","BLACK")
 D LOCATE^TTRNSI(2,1)
 F I=1:1:80 D LOCATE^TTRNSI(2,I) W BOX("H")
 D LOCATE^TTRNSI(23,1)
 F I=1:1:80 D LOCATE^TTRNSI(23,I) W BOX("H")
 D LOCATE^TTRNSI(3,1)
 Q

ERROR
 N ESEV,EMSG,ENTREF,ELINE,ECODE,MCODE,GTMERR,IO,PID
 S PID=$JOB
 S IO=$IO
 S MCODE=$P($EC,",",2)
 S ECODE=$P($ZS,",",1)
 S ENTREF=$P($ZS,",",2)
 S GTMERR=$P($ZS,",",3)
 S EMSG=$P($ZS,",",4,$L($ZS,","))
 S ESEV=$P(GTMERR,"-",2)
 D RESET^TTRNSI
 W "IGLS ERROR",!,!
 W " PID:                ",PID,!
 W " IO:                 ",IO,!,!
 W " ANSI ERROR CODE:    ",MCODE,!
 W " GT.M ERROR CODE:    ",ECODE,!
 W " ERROR MESSAGE:      ",EMSG,!
 W " SEVERITY:           ",ESEV,!,!
 W " ENTRYREF:           ",ENTREF,!,!
 ZP @ENTREF
 W "PRESS ANY KEY TO CONTINUE",!
 R *TMP
 BREAK
 Q

RESET
 D ESC^TTRNSI("c")
 Q
