TTAPPT
 Q

;
; DATA STRUCTURE
;
;  Global State:
;    Next appointment key: ^TT("COMPANY","APPTKEY")
;
;  Schedule blocks:
;    ^TT("SBLK",USER,DATE,HOUR,MINUTE,INDEX)=APPTKEY
;
;  Appointments:
;    ^TT("APPT",APPTKEY)
;

DAYCAL(STARTDATE,STARTHOUR,STARTAMPM)
 N STARTHR,ENDHR,CURROW,CUR,CURDATE,AMPM
 S CURDATE=$G(STARTDATE,$ZD($H,"MM/DD/YYYY"))
 S STARTHR=$G(STARTHOUR,$$CURHOUR^TTDATE),ENDHR=STARTHR+4
 S AMPM=$G(STARTAMPM,$$CURAMPM^TTDATE)
REDISPLAY
 S CURROW=3
 D INIT^TT,CAPTION^TTUI("DAY CALENDAR "_CURDATE)
 F I=STARTHR:1:ENDHR  D
 . S CUR=I 
 . I CUR>12 D 
 . . S CUR=CUR-12
 . . I AMPM="AM" S AMPM="PM" E  S AMPM="PM"
 . D LOCATE^TTRNSI(CURROW,1) 
 . D SETATTR^TTRNSI("REVERSE")
 . W $J(CUR,2),":00"
 . D SETATTR^TTRNSI("RESET")
 . D SETCOLOR^TTRNSI("GREEN","BLACK")
 . W " ",AMPM
 . D LOCATE^TTRNSI(CURROW+1,3) W ":15"
 . D LOCATE^TTRNSI(CURROW+2,3) W ":30"
 . D LOCATE^TTRNSI(CURROW+3,3) W ":45"
 . S CURROW=CURROW+4
 D HOME^TTRNSI
 R *TMP
 Q

ADD(TITLE,LOCATION,COLOR)
 N KEY
 S KEY=^TT("COMPANY","APPTKEY")
 S ^TT("COMPANY","APPTKEY")=^TT("COMPANY","APPTKEY")+1
 TS
 S ^TT("APPT",KEY,"TITLE")=TITLE
 S ^TT("APPT",KEY,"LOCATION")=LOCATION
 S ^TT("APPT",KEY,"COLOR")=COLOR
 TC
 Q KEY

SCHEDULE(USER,KEY,DATE,STARTTIME,ENDTIME)
 N HR,MIN,CURTIME 
 S $P(STARTTIME,":",2)=$P(STARTTIME,":",2)-15
 S CURTIME=STARTTIME,HR="",MIN=""
 F  Q:(HR=$P(ENDTIME,":",1))&(MIN=$P(ENDTIME,":",2))  D
 . S HR=$P(CURTIME,":",1),MIN=$P(CURTIME,":",2)
 . I MIN=45 D
 . . S $P(CURTIME,":",1)=HR+1,$P(CURTIME,":",2)=0,MIN=0,HR=HR+1
 . E  D
 . . S MIN=MIN+15
 . S CURTIME=HR_":"_MIN
 . S ^TT("SBLK",USER,DATE,HR,MIN)=KEY
 Q

SETUP
 S ^TT("COMPANY","APPTKEY")=100
 Q