TTCVACCT
 N RESULT,RETURN,USERNAME,PASSWORD,FLAGS
 N NEST,EGGDEF,EMBDEF,DA,EGGNAME
 ;
 S USERNAME="JPW",PASSWORD="",FLAGS="V"
 S NEST="IGLS",EGGNAME="ACCOUNTS"
 ;
 S EGGDEF(EGGNAME,"ENTRYNUMBER")=1
 S EGGDEF(EGGNAME,"EMBRYOS")=""
 ;
 S EMBDEF("NUMBER","TYPE")="NUMBER"
 S EMBDEF("NUMBER","UNIQUE")=1
 S EMBDEF("NUMBER","REQUIRED")=1
 S EMBDEF("NUMBER","PRIMARY")=1
 S EMBDEF("NAME","MAXLENGTH")=80
 S EMBDEF("NAME","TYPE")="STRING"
 S EMBDEF("NAME","REQUIRED")=1
 S EMBDEF("NAME","INPUTXFORM")="S RKOUT=$TR(RKIN,""abcdefghijklmnopqrstuvwxyz"",""ABCDEFGHIJKLMNOPQRSTUVWXYZ"")"
 S EMBDEF("PERSISTENCE","TYPE")="STRING"
 S EMBDEF("PERSISTENCE","REQUIRED")=1
 S EMBDEF("PERSISTENCE","MAXLENGTH")=9
 S EMBDEF("SEQ","TYPE")="NUMBER"
 S EMBDEF("SEQ","REQUIRED")=1
 S EMBDEF("TYPE","TYPE")="STRING"
 S EMBDEF("TYPE","MAXLENGTH")=9
 S EMBDEF("TYPE","REQUIRED")=1
 ;
 S RETURN=$$CONNECT^ROOK(USERNAME,PASSWORD,FLAGS,.RESULT)
 S RETURN=$$MKNEST^ROOKDD(NEST,.RESULT)
 S RETURN=$$USE^ROOK(NEST,.RESULT)
 S RETURN=$$MKEGG^ROOKDD(.EGGDEF,.RESULT)
 S RETURN=$$MKEMBRYO^ROOKDD(EGGNAME,.EMBDEF,.RESULT)
 ;
 D TRANSTART^ROOKDM
 ;
 N ANUM,NAME,PERS,SEQ,TYPE,ENT,EN S EN=EGGNAME
 S ANUM="",ENT=1
 F  S ANUM=$O(^TT("ACCT",ANUM)) Q:ANUM=""  D
 . S NAME=^TT("ACCT",ANUM)
 . S PERS=^TT("ACCT",ANUM,"PERSISTENCE")
 . S SEQ=^TT("ACCT",ANUM,"SEQ")
 . S TYPE=^TT("ACCT",ANUM,"TYPE")
 . S DA(EN,ENT,"NUMBER")=ANUM
 . S DA(EN,ENT,"NAME")=NAME
 . S DA(EN,ENT,"PERSISTENCE")=PERS
 . S DA(EN,ENT,"SEQ")=SEQ
 . S DA(EN,ENT,"TYPE")=TYPE
 . S RETURN=$$INSERT^ROOKDM(.DA,.RESULT)
 . S ENT=$I(ENT)
 ;
 S RETURN=$$TRANCOMMIT^ROOKDM(.RESULT)
 Q