TTENTRY
 Q

CHOOSE(CHOSEN)
 N MA,CUSTCODE,CURCUST,CURENTR,ENTRIDX S ENTRIDX=""
 N CUSTRES,ITMTITLE
 S CUSTCODE=$$CHOOSE^TTCUST(.CURCUST)
 S MA("TITLE")="TIME ENTRY"
 F  S ENTRIDX=$O(^TT("ENTR",CUSTCODE,ENTRIDX)) Q:ENTRIDX=""  D
 . S ITMTITLE=^TT("ENTR",CUSTCODE,ENTRIDX,"DATE")
 . S ITMTITLE=ITMTITLE_" ("
 . S ITMTITLE=ITMTITLE_^TT("ENTR",CUSTCODE,ENTRIDX,"HOURS")_" HOURS)"
 . S MA("ITEMS",ITMTITLE)="S CURENTR="""_ENTRIDX_""""
 D GO^TTMENU(.MA)
 M CHOSEN=^TT("ENTR",CUSTCODE,ENTRIDX)
 Q CURENTR

CREATE
 N HOURS,DATE,TASK,CUSTCODE,ENTRIDX,CUSTREC
GCODE
 S CUSTCODE=$$CHOOSE^TTCUST(.CUSTREC)
 I $G(^TT("CUSTOMER",CUSTCODE))="" W !,"INVALID CUSTOMER CODE" G GCODE
 W !,"RESPOND DATE "
 S DATE=$$CHOOSE^TTDATE
 W !,"RESPOND TASK PERFORMED "
 R TASK
 W !,"RESPOND HOURS "
 R HOURS
 S ENTRIDX=^TT("CUSTOMER",CUSTCODE,"ENTRIDX")
 TS
 S ^TT("ENTR",CUSTCODE,ENTRIDX,"HOURS")=HOURS
 S ^TT("ENTR",CUSTCODE,ENTRIDX,"DATE")=DATE
 S ^TT("ENTR",CUSTCODE,ENTRIDX,"TASK")=TASK
 S ^TT("ENTR",CUSTCODE,ENTRIDX,"BILLED")="NO"
 S ^TT("ENTR",CUSTCODE,ENTRIDX,"CUSTCODE")=CUSTCODE
 S ^TT("CUSTOMER",CUSTCODE,"ENTRIDX")=^TT("CUSTOMER",CUSTCODE,"ENTRIDX")+1
 TC
 Q
