TTENTRY
 Q

CHOOSE(CHOSEN)
 N MA,CUSTCODE,CURCUST,CURENTR,ENTRIDX S ENTRIDX=""
 N CUSTRES,ITMTITLE
 S CUSTCODE=$$CHOOSE^TTCUST(.CURCUST)
 S MA("TITLE")="TIME ENTRY"
 F  S ENTRIDX=$O(^TT("ENTR",CUSTCODE,ENTRIDX)) Q:ENTRIDX=""  D
 . S ITMTITLE=^TT("ENTR",CUSTCODE,ENTRIDX,"DATE")
 . S ITMTITLE=ITMTITLE_" ("
 . S ITMTITLE=ITMTITLE_^TT("ENTR",CUSTCODE,ENTRIDX,"HOURS")_" HOURS)"
 . S MA("ITEMS",ITMTITLE)="S CURENTR="""_ENTRIDX_""""
 D GO^TTMENU(.MA)
 M CHOSEN=^TT("ENTR",CUSTCODE,ENTRIDX)
 Q CURENTR

CREATE
 N FA
 S FA("TITLE")="NEW TIME ENTRY"
 S FA("ITEMS",1,"NAME")="TASK"
 S FA("ITEMS",1,"LABEL")="TASK PERFORMED:"
 S FA("ITEMS",1,"LABEL","TOP")=4
 S FA("ITEMS",1,"LABEL","LEFT")=24
 S FA("ITEMS",1,"FIELD","TOP")=4
 S FA("ITEMS",1,"FIELD","LEFT")=40
 S FA("ITEMS",1,"FIELD","MAXLENGTH")=35
 S FA("ITEMS",1,"FIELD","REQUIRED")=1
 S FA("ITEMS",2,"NAME")="DATE"
 S FA("ITEMS",2,"LABEL")="DATE:"
 S FA("ITEMS",2,"LABEL","TOP")=6
 S FA("ITEMS",2,"LABEL","LEFT")=34
 S FA("ITEMS",2,"FIELD","TOP")=6
 S FA("ITEMS",2,"FIELD","LEFT")=40
 S FA("ITEMS",2,"FIELD","MAXLENGTH")=10
 S FA("ITEMS",2,"FIELD","REQUIRED")=1
 S FA("ITEMS",2,"FIELD","ONFOCUS")="D CHOOSE^TTDATE($ZDATE($H))"
 S FA("ITEMS",3,"NAME")="HOURS"
 S FA("ITEMS",3,"LABEL")="HOURS:"
 S FA("ITEMS",3,"LABEL","TOP")=8
 S FA("ITEMS",3,"LABEL","LEFT")=33
 S FA("ITEMS",3,"FIELD","TOP")=8
 S FA("ITEMS",3,"FIELD","LEFT")=40
 S FA("ITEMS",3,"FIELD","MAXLENGTH")=8
 S FA("ITEMS",3,"FIELD","REQUIRED")=1
 S FA("ITEMS",4,"NAME")="CUSTOMER"
 S FA("ITEMS",4,"LABEL")="CUSTOMER:"
 S FA("ITEMS",4,"LABEL","TOP")=10
 S FA("ITEMS",4,"LABEL","LEFT")=30
 S FA("ITEMS",4,"FIELD","TOP")=10
 S FA("ITEMS",4,"FIELD","LEFT")=40
 S FA("ITEMS",4,"FIELD","MAXLENGTH")=30
 S FA("ITEMS",4,"FIELD","REQUIRED")=1
 S FA("ITEMS",4,"FIELD","ONFOCUS")="S I=$$CHOOSE^TTCUST(.B)"
 D GO^TTFORM(.FA)
 G:CANFLG=1 CANCELCREATE
 N HOURS,DATE,TASK,CUSTCODE,ENTRIDX,CUSTREC
 S CUSTCODE=$$GETINTVAL^TTFORM(.FA,"CUSTOMER")
 S DATE=$$GETINTVAL^TTFORM(.FA,"DATE")
 S TASK=$$GETEXTVAL^TTFORM(.FA,"TASK")
 S HOURS=$$GETEXTVAL^TTFORM(.FA,"HOURS")
 S ENTRIDX=^TT("CUSTOMER",CUSTCODE,"ENTRIDX")
 TS
 S ^TT("ENTR",CUSTCODE,ENTRIDX,"HOURS")=HOURS
 S ^TT("ENTR",CUSTCODE,ENTRIDX,"DATE")=DATE
 S ^TT("ENTR",CUSTCODE,ENTRIDX,"TASK")=TASK
 S ^TT("ENTR",CUSTCODE,ENTRIDX,"BILLED")="NO"
 S ^TT("ENTR",CUSTCODE,ENTRIDX,"CUSTCODE")=CUSTCODE
 S ^TT("CUSTOMER",CUSTCODE,"ENTRIDX")=^TT("CUSTOMER",CUSTCODE,"ENTRIDX")+1
 TC
CANCELCREATE
 Q

