TTFILE
 Q
 
VIEW(FILE,CAPTION)
 N EV,KEY,CONTENTS,STARTLINE,SCRLINE,LINES 
 S LINES=0,SCRLINE=3,STARTLINE=1
 S LINES=$$LOAD(FILE,.CONTENTS)
REDISPLAY
 D INIT^TT
 D CAPTION^TTUI(CAPTION)
 D SETCOLOR^TTRNSI("CYAN","BLACK")
 S SCRLINE=3
 F I=STARTLINE:1:STARTLINE+19  D
 . D LOCATE^TTRNSI(SCRLINE,1)
 . W $G(CONTENTS(I))
 . S SCRLINE=SCRLINE+1
IO
 D LOCATE^TTRNSI(24,1),SETCOLOR^TTRNSI("MAGENTA","BLACK")
 D SETATTR^TTRNSI("BRIGHT") W "F3:MAIL     F6:EXIT"
 D HOME^TTRNSI
 S QUITFLG=0
 S KEY=$$GETCH^%TERMIO(.EV)
 I KEY="KEY_UP" D
 . I STARTLINE>0 S STARTLINE=STARTLINE-1 G REDISPLAY
 I KEY="KEY_DOWN" D 
 . I STARTLINE<(LINES-19) S STARTLINE=STARTLINE+1 G REDISPLAY
 I KEY="KEY_F6" S QUITFLG=1
 I KEY="KEY_F3" D
 . D MAIL(FILE,CAPTION)
 G:QUITFLG=0 REDISPLAY
 D RESET^TTRNSI
 Q
 ;
MAIL(FILE,CAPTION)
 N FA
 S FA("TITLE")="MAIL "_CAPTION
 S FA("ITEMS",1,"NAME")="TO"
 S FA("ITEMS",1,"LABEL")="TO: "
 S FA("ITEMS",1,"LABEL","TOP")=8
 S FA("ITEMS",1,"LABEL","LEFT")=40-$L(FA("ITEMS",1,"LABEL"))
 S FA("ITEMS",1,"FIELD","TOP")=8
 S FA("ITEMS",1,"FIELD","LEFT")=40
 S FA("ITEMS",1,"FIELD","MAXLENGTH")=35
 S FA("ITEMS",1,"FIELD","REQUIRED")=1
 S FA("ITEMS",1,"FIELD","PRESERVECASE")=1
 D GO^TTFORM(.FA)
 N TO S TO=$$GETEXTVAL^TTFORM(.FA,"TO")
 D MAILTO^TTNET(TO,$TR(CAPTION," ","_"),"FILEBODY.TXT",FILE)
 Q

LOAD(FILE,CONTENTS)
 N LINES,CURLINE S (LINES,CURLINE)=0
 O FILE:READONLY
 U FILE
 F  S CURLINE=CURLINE+1 R CONTENTS(CURLINE) Q:$ZEOF 
 S LINES=CURLINE
 U $P
 C FILE
 Q LINES
 
  
 