TTFILE
 Q

VIEW(FILE,CAPTION)
 N EV,CONTENTS,STARTLINE,SCRLINE,LINES 
 S LINES=0,SCRLINE=3,STARTLINE=1
 S LINES=$$LOAD(FILE,.CONTENTS)
REDISPLAY
 D INIT^TT
 D CAPTION^TTUI(CAPTION)
 D SETCOLOR^TTRNSI("CYAN","BLACK")
 S SCRLINE=3
 F I=STARTLINE:1:STARTLINE+19  D
 . D LOCATE^TTRNSI(SCRLINE,1)
 . W $G(CONTENTS(I))
 . S SCRLINE=SCRLINE+1
 . I I=LINES G IO
IO
 D LOCATE^TTRNSI(24,1),SETCOLOR^TTRNSI("MAGENTA","BLACK")
 D SETATTR^TTRNSI("BRIGHT") W "ENTER:SAVE Q:QUIT E:EMAIL"
 S QUITFLG=0
 D GET^TTIO(.EV)
 I $G(EV("CONTROL"))="UP" D
 . I STARTLINE'=1 S STARTLINE=STARTLINE-1 G REDISPLAY
 I $G(EV("CONTROL"))="DOWN" D 
 . I STARTLINE'=LINES S STARTLINE=STARTLINE+1 G REDISPLAY
 I $G(EV("CHARACTER",1))="Q"!"q" S QUITFLG=1
 I 'QUITFLG G REDISPLAY
 D ESC^TTRNSI("c")
 Q
 

LOAD(FILE,CONTENTS)
 N LINES,CURLINE S (LINES,CURLINE)=0
 O FILE:READONLY
 U FILE
 F  S CURLINE=CURLINE+1 R CONTENTS(CURLINE) Q:$ZEOF 
 S LINES=CURLINE
 U $P
 C FILE
 Q LINES
 
  
 