TTFILE
 Q
 
VIEW(FILE,CAPTION)
 N EV,KEY,CONTENTS,STARTLINE,SCRLINE,LINES 
 S LINES=0,SCRLINE=3,STARTLINE=1
 S LINES=$$LOAD(FILE,.CONTENTS)
REDISPLAY
 D INIT^TT
 D CAPTION^TTUI(CAPTION)
 D SETCOLOR^TTRNSI("CYAN","BLACK")
 S SCRLINE=3
 F I=STARTLINE:1:STARTLINE+19  D
 . D LOCATE^TTRNSI(SCRLINE,1)
 . W $G(CONTENTS(I))
 . S SCRLINE=SCRLINE+1
IO
 D LOCATE^TTRNSI(24,1),SETCOLOR^TTRNSI("MAGENTA","BLACK")
 D SETATTR^TTRNSI("BRIGHT") W "F3:MAIL     F6:EXIT     F9:SAVE"
 D HOME^TTRNSI
 S QUITFLG=0
 S KEY=$$GETCH^%TERMIO(.EV)
 I KEY="KEY_UP" D
 . I STARTLINE>0 S STARTLINE=STARTLINE-1 G REDISPLAY
 I KEY="KEY_DOWN" D 
 . I STARTLINE<(LINES-19) S STARTLINE=STARTLINE+1 G REDISPLAY
 I KEY="KEY_F6" S QUITFLG=1
 G:QUITFLG=0 REDISPLAY
 D RESET^TTRNSI
 Q
 

LOAD(FILE,CONTENTS)
 N LINES,CURLINE S (LINES,CURLINE)=0
 O FILE:READONLY
 U FILE
 F  S CURLINE=CURLINE+1 R CONTENTS(CURLINE) Q:$ZEOF 
 S LINES=CURLINE
 U $P
 C FILE
 Q LINES
 
  
 