TTIMPORT
 N MA
 S MA("TITLE")="IMPORT/EXPORT"
 S MA("ITEMS","IMPORT ACCOUNTING DATA FROM CSV")="D ICSVACCT^TTIMPORT"
 S MA("ITEMS","IMPORT ACCOUNTING DATA FROM CSV","KEY")="XKGLS:M"
 S MA("ITEMS","IMPORT INVOICING DATA FROM CSV")="D ICSVINV^TTIMPORT"
 S MA("ITEMS","IMPORT INVOICING DATA FROM CSV","KEY")="XKGLS:M"
 S MA("ITEMS","IMPORT PAYMENT DATA FROM CSV")="D ICSVPMT^TTIMPORT"
 S MA("ITEMS","IMPORT PAYMENT DATA FROM CSV","KEY")="XKGLS:M"
 S MA("ITEMS","EXPORT ACCOUNTING DATA TO CSV")="D ICSVACCT^TTEXPORT"
 S MA("ITEMS","EXPORT ACCOUNTING DATA TO CSV","KEY")="XKGLS:V"
 S MA("ITEMS","EXPORT INVOICING DATA TO CSV")="D ICSVINV^TTEXPORT"
 S MA("ITEMS","EXPORT INVOICING DATA TO CSV","KEY")="XKGLS:V"
 S MA("ITEMS","EXPORT PAYMENT DATA TO CSV")="D ICSVPMT^TTEXPORT"
 S MA("ITEMS","EXPORT PAYMENT DATA TO CSV","KEY")="XKGLS:V"
 S MA("ITEMS","IMPORT TIME COLLECTION DATA FROM CSV")="D ICSVTC^TTIMPORT"
 S MA("ITEMS","IMPORT TIME COLLECTION DATA FROM CSV","KEY")="XKTC:M"
 S MA("ITEMS","EXPORT TIME COLLECTION DATA TO CSV")="D ICSVTC^TTEXPORT"
 S MA("ITEMS","EXPORT TIME COLLECTION DATA TO CSV","KEY")="XKTC:V"
 S MA("ITEMS","QUIT TO MAIN MENU")="D ^TT"
 D GO^TTMENU(.MA)
 Q

ICSVACCT
 N FILE,RECORDS S RECORDS=0
 D INIT^TT,CAPTION^TTUI("IMPORT ACCOUNTING DATA FROM CSV")
 D LOCATE^TTRNSI(3,1),SETCOLOR^TTRNSI("GREEN","BLACK")
 W "RESPOND HOST FILE "
 R FILE
 S RECORDS=$$CSVACCT(FILE)
 D MSGBOX^TTUI("IMPORTED "_RECORDS_" RECORDS FROM "_FILE,0,"IMPORT CSV")
 Q

;
; CSV format:
; CHKNUM,DATE,JNL,PERIOD,CREDIT,DEBIT,AMT
;
CSVACCT(FILE)
 N CONT,IDX,LINES,LINE S IDX=""
 N CHKNUM,DATE,JNL,PERIOD,CREDIT,DEBIT,AMT
 S LINES=$$LOAD^TTFILE("TT/IMPORT/"_FILE,.CONT)
 F  S IDX=$O(CONT(IDX)) Q:IDX=""  D
 . S LINE=CONT(IDX)
 . S CHKNUM=$P(LINE,",",1)
 . S DATE=$P(LINE,",",2)
 . S JNL=$P(LINE,",",3)
 . S PERIOD=$P(LINE,",",4)
 . S CREDIT=$P(LINE,",",5)
 . S DEBIT=$P(LINE,",",6)
 . S AMT=$P(LINE,",",7)
 . I AMT'="" D
 . . D POST^TTACCOUNT(DATE,AMT,CREDIT,DEBIT,PERIOD,JNL,CHKNUM)
 Q LINES

ICSVINV
 N FILE,RECORDS S RECORDS=0
 D INIT^TT,CAPTION^TTUI("IMPORT INVOICING DATA FROM CSV")
 D LOCATE^TTRNSI(3,1),SETCOLOR^TTRNSI("GREEN","BLACK")
 W "RESPOND HOST FILE "
 R FILE
 S RECORDS=$$CSVINV(FILE)
 D MSGBOX^TTUI("IMPORTED "_RECORDS_" RECORDS FROM "_FILE,0,"IMPORT CSV")
 Q
;
;"CUSTOMER",CUSTCODE,"PAYMENTS",PMTIDX:
;	DATE
;	CHKNUM
;	MEMO
;	AMOUNT
;	NMGRTAMOUNT
;CUSTCODE,INVIDX,DATE,TOTAL,HOURS,RATEHOUR,PAID,DAYSTOPAY
CSVINV(FILE)
 N CONT,IDX,LINES,LINE S IDX=""
 N CUSTCODE,INVIDX,DATE,TOTAL,HOURS,RATEHOUR,PAID,DAYSTOPAY
 S LINES=$$LOAD^TTFILE("TT/IMPORT/"_FILE,.CONT)
 F  S IDX=$O(CONT(IDX)) Q:IDX=""  D
 . S LINE=CONT(IDX)
 . S CUSTCODE=$P(LINE,",",1)
 . S INVIDX=$P(LINE,",",2)
 . S DATE=$P(LINE,",",3)
 . S TOTAL=$P(LINE,",",4)
 . S HOURS=$P(LINE,",",5)
 . S RATEHOUR=$P(LINE,",",6)
 . S PAID=$P(LINE,",",7)
 . S DAYSTOPAY=$P(LINE,",",8)
 D CREATE(CUSTCODE,INVIDX,DATE,TOTAL,HOURS,RATEHOUR,PAID,DAYSTOPAY)
 Q LINES

;
;"CUSTOMER",CUSTCODE,"INV",INVIDX:
;	TOTAL
;	HOURS
;	RATEHOUR
;	PAID
;	DAYSTOPAY
;
CREATE(CUSTCODE,INVIDX,DATE,TOTAL,HOURS,RATEHOUR,PAID,DAYSTOPAY)
 TS
 S ^TT("CUSTOMER",CUSTCODE,"INV",INVIDX,"DATE")=DATE
 S ^TT("CUSTOMER",CUSTCODE,"INV",INVIDX,"TOTAL")=TOTAL
 S ^TT("CUSTOMER",CUSTCODE,"INV",INVIDX,"HOURS")=HOURS
 S ^TT("CUSTOMER",CUSTCODE,"INV",INVIDX,"RATEHOUR")=RATEHOUR
 S ^TT("CUSTOMER",CUSTCODE,"INV",INVIDX,"PAID")=PAID
 S ^TT("CUSTOMER",CUSTCODE,"INV",INVIDX,"DAYSTOPAY")=DAYSTOPAY
 TC
 Q
