TTMENU
 Q

GO(MA,CAPTION)
 N CHOICE,FIRST,INDEX,ITM,RESULT,EV S (FIRST,ITM)="",IDX=1
 S CHOICE=1
 F  S ITM=$O(MA("ITEMS",ITM)) Q:ITM=""  D
 . S MA("INDEX",IDX)=ITM
 . S MA("ITEMS",ITM,"INDEX")=IDX
 . S IDX=IDX+1
REDISPLAY
 I '$$VALCHOICE(.MA,CHOICE) D
 . I CHOICE'=$$MAXHEIGHT(.MA) D
 . . S CHOICE=CHOICE+1 G REDISPLAY
 . E  S CHOICE=1 G REDISPLAY
 U $P:NOESCAPE
 D INIT^TT
 D LOCATE^TTRNSI(24,1),SETCOLOR^TTRNSI("MAGENTA","BLACK")
 W "ARROW KEYS TO NAVIGATE; ENTER SELECTS"
 N WIDTH,ROWS S (WIDTH,ROWS)=0
 N CAPLEFT,LEFT,TOP S (CAPLEFT,LEFT,TOP)=0
 S WIDTH=$$MAXWIDTH(.MA)
 S LEFT=(80/2)-(WIDTH/2)
 S LEFT=$P(LEFT,".",1)
 S ROWS=$$MAXHEIGHT(.MA)
 S TOP=((24/2)-(ROWS/2))+1
 S TOP=$P(TOP,".",1)
 I $G(CAPTION,"")="" D CAPTION^TTUI(MA("TITLE"))
 I $G(CAPTION,"")'="" D CAPTION^TTUI(CAPTION)
 D SETATTR^TTRNSI("RESET")
 D SETCOLOR^TTRNSI("GREEN","BLACK")
 N EV,ITEM,ROW S ITEM="",ROW=TOP
 F  S ITEM=$O(MA("ITEMS",ITEM)) Q:ITEM=""  D
 . I MA("ITEMS",ITEM,"INDEX")=CHOICE D SETATTR^TTRNSI("REVERSE")
 . I MA("ITEMS",ITEM,"INDEX")'=CHOICE D 
 . . I $$HASCRED(.MA,ITEM) D 
 . . . D SETATTR^TTRNSI("RESET"),SETCOLOR^TTRNSI("GREEN","BLACK")
 . . E  D SETATTR^TTRNSI("RESET"),SETCOLOR^TTRNSI("WHITE","BLACK")
 . D LOCATE^TTRNSI(ROW,LEFT) W ITEM,! D SETCOLOR^TTRNSI("GREEN","BLACK")
 . S ROW=ROW+1
 D HOME^TTRNSI
IO
 S RESULT=$$GETCH^%TERMIO(.EV)
 I RESULT="KEY_UP" D
 . I CHOICE'=1 D
 . . S CHOICE=CHOICE-1 
 . . G REDISPLAY
 I RESULT="KEY_DOWN" D
 . I CHOICE'=$$MAXHEIGHT(.MA) S CHOICE=CHOICE+1 G REDISPLAY
 I RESULT="KEY_ENTER" D
 . S ITM=MA("INDEX",CHOICE)
 . S RESULT=""
 . X MA("ITEMS",ITM)
 Q

HASCRED(MA,ITEM)
 N KEYSTR,RETVAL,KEY,GRANT
 I $G(MA("ITEMS",ITEM,"KEY"))="" S RETVAL=1
 I $G(MA("ITEMS",ITEM,"KEY"))'="" D
 . S KEYSTR=MA("ITEMS",ITEM,"KEY") 
 . S KEY=$P(KEYSTR,":",1)
 . S GRANT=$P(KEYSTR,":",2)
 . S RETVAL=$$CRED^TTAUTH(TTUSER,KEY,GRANT)
 Q RETVAL
 
VALCHOICE(MA,CHOICE)
 N KEYSTR,ITM,ITME,RETVAL,KEY,GRANT
 S ITME=MA("INDEX",CHOICE)
 M ITM=MA("ITEMS",ITME)
 I $G(MA("ITEMS",ITME,"KEY"))="" S RETVAL=1
 I $G(MA("ITEMS",ITME,"KEY"))'="" D
 . S KEYSTR=MA("ITEMS",ITME,"KEY") 
 . S KEY=$P(KEYSTR,":",1)
 . S GRANT=$P(KEYSTR,":",2)
 . S RETVAL=$$CRED^TTAUTH(TTUSER,KEY,GRANT)
 Q RETVAL


MAXHEIGHT(MA)
 N HEIGHT,ITEM S HEIGHT=0,ITEM=""
 F  S ITEM=$O(MA("ITEMS",ITEM)) Q:ITEM=""  D
 . S HEIGHT=HEIGHT+1
 Q HEIGHT

MAXWIDTH(MA)
 N MAX,ITEM S MAX=0,ITEM=""
 F  S ITEM=$O(MA("ITEMS",ITEM)) Q:ITEM=""  D
 . I $L(ITEM)>MAX S MAX=$L(ITEM)
 Q MAX
 