TTMENU
 Q

GO(MA,CAPTION)
 N CHOICE,FIRST,INDEX,ITM S (FIRST,ITM)="",IDX=1
 S CHOICE=1
 F  S ITM=$O(MA("ITEMS",ITM)) Q:ITM=""  D
 . S MA("INDEX",IDX)=ITM
 . S MA("ITEMS",ITM,"INDEX")=IDX
 . S IDX=IDX+1
REDISPLAY
 U $P:NOESCAPE
 D INIT^TT
 D LOCATE^TTRNSI(24,1),SETCOLOR^TTRNSI("MAGENTA","BLACK")
 W "ARROW KEYS TO NAVIGATE; ENTER SELECTS"
 N WIDTH,ROWS S (WIDTH,ROWS)=0
 N CAPLEFT,LEFT,TOP S (CAPLEFT,LEFT,TOP)=0
 S WIDTH=$$MAXWIDTH(.MA)
 S LEFT=(80/2)-(WIDTH/2)
 S LEFT=$P(LEFT,".",1)
 S ROWS=$$MAXHEIGHT(.MA)
 S TOP=((24/2)-(ROWS/2))+1
 S TOP=$P(TOP,".",1)
 I $G(CAPTION,"")="" D CAPTION^TTUI(MA("TITLE"))
 I $G(CAPTION,"")'="" D CAPTION^TTUI(CAPTION)
 D SETATTR^TTRNSI("RESET")
 D SETCOLOR^TTRNSI("GREEN","BLACK")
 N EV,ITEM,ROW S ITEM="",ROW=TOP
 F  S ITEM=$O(MA("ITEMS",ITEM)) Q:ITEM=""  D
 . I MA("ITEMS",ITEM,"INDEX")=CHOICE D SETATTR^TTRNSI("REVERSE")
 . I MA("ITEMS",ITEM,"INDEX")'=CHOICE D SETATTR^TTRNSI("RESET"),SETCOLOR^TTRNSI("GREEN","BLACK")
 . D LOCATE^TTRNSI(ROW,LEFT) W ITEM,!
 . S ROW=ROW+1
IO
 D GET^TTIO(.EV)
 I $G(EV("CONTROL"))="UP" D
 . I CHOICE'=1 S CHOICE=CHOICE-1 G REDISPLAY
 I $G(EV("CONTROL"))="DOWN" D
 . I CHOICE'=$$MAXHEIGHT(.MA) S CHOICE=CHOICE+1 G REDISPLAY
 I $G(EV("CONTROL"))="ENTER" D
 . S ITM=MA("INDEX",CHOICE)
 . X MA("ITEMS",ITM)
 Q

MAXHEIGHT(MA)
 N HEIGHT,ITEM S HEIGHT=0,ITEM=""
 F  S ITEM=$O(MA("ITEMS",ITEM)) Q:ITEM=""  D
 . S HEIGHT=HEIGHT+1
 Q HEIGHT

MAXWIDTH(MA)
 N MAX,ITEM S MAX=0,ITEM=""
 F  S ITEM=$O(MA("ITEMS",ITEM)) Q:ITEM=""  D
 . I $L(ITEM)>MAX S MAX=$L(ITEM)
 Q MAX
 