TTNET
 Q

MAILCUST(CUST,SUBJECT,BODY,FILENAME)
 N COMLINE S COMLINE="mutt -i 'TT/"_BODY_"' -s "_SUBJECT_" -a "_FILENAME_" -- "_^TT("CUSTOMER",CUST,"EMAIL")_" < /dev/null"
 ZSYSTEM COMLINE
 Q

MAILTO(EMAIL,SUBJECT,BODY,ATTACH)
 N COMLINE S COMLINE="mutt -i 'TT/"_BODY_"' -s "_SUBJECT_" -a "_FILENAME_" -- "_EMAIL_" < /dev/null"
 ZSYSTEM COMLINE
 Q
