TTPAYMENT
 Q

RECEIVE
 N FA
 S FA("TITLE")="RECEIVE PAYMENT"
 S FA("ITEMS",1,"NAME")="AMOUNT"
 S FA("ITEMS",1,"LABEL")="AMOUNT:"
 S FA("ITEMS",1,"LABEL","TOP")=4
 S FA("ITEMS",1,"LABEL","LEFT")=32
 S FA("ITEMS",1,"FIELD","TOP")=4
 S FA("ITEMS",1,"FIELD","LEFT")=40
 S FA("ITEMS",1,"FIELD","MAXLENGTH")=10
 S FA("ITEMS",1,"FIELD","REQUIRED")=1
 S FA("ITEMS",2,"NAME")="CHKNO"
 S FA("ITEMS",2,"LABEL")="CHECK NUMBER:"
 S FA("ITEMS",2,"LABEL","TOP")=6
 S FA("ITEMS",2,"LABEL","LEFT")=26
 S FA("ITEMS",2,"FIELD","TOP")=6
 S FA("ITEMS",2,"FIELD","LEFT")=40
 S FA("ITEMS",2,"FIELD","MAXLENGTH")=10
 S FA("ITEMS",2,"FIELD","REQUIRED")=1 
 S FA("ITEMS",3,"NAME")="PMTDATE"
 S FA("ITEMS",3,"LABEL")="PAYMENT DATE:"
 S FA("ITEMS",3,"LABEL","TOP")=8
 S FA("ITEMS",3,"LABEL","LEFT")=26
 S FA("ITEMS",3,"FIELD","TOP")=8
 S FA("ITEMS",3,"FIELD","LEFT")=40
 S FA("ITEMS",3,"FIELD","MAXLENGTH")=10
 S FA("ITEMS",3,"FIELD","REQUIRED")=1
 S FA("ITEMS",3,"FIELD","ONFOCUS")="D CHOOSE^TTDATE($ZDATE($H),""CHOOSE PAYMENT DATE"")"
 S FA("ITEMS",4,"NAME")="MEMO"
 S FA("ITEMS",4,"LABEL")="MEMO:"
 S FA("ITEMS",4,"LABEL","TOP")=10
 S FA("ITEMS",4,"LABEL","LEFT")=34
 S FA("ITEMS",4,"FIELD","TOP")=10
 S FA("ITEMS",4,"FIELD","LEFT")=40
 S FA("ITEMS",4,"FIELD","MAXLENGTH")=30
 S FA("ITEMS",4,"FIELD","REQUIRED")=1
 S FA("ITEMS",5,"NAME")="NMGRT"
 S FA("ITEMS",5,"LABEL")="NMGRT AMOUNT:"
 S FA("ITEMS",5,"LABEL","TOP")=12
 S FA("ITEMS",5,"LABEL","LEFT")=26
 S FA("ITEMS",5,"FIELD","TOP")=12
 S FA("ITEMS",5,"FIELD","LEFT")=40
 S FA("ITEMS",5,"FIELD","MAXLENGTH")=10
 S FA("ITEMS",5,"FIELD","REQUIRED")=1
 S FA("ITEMS",6,"NAME")="CUSTOMER"
 S FA("ITEMS",6,"LABEL")="CUSTOMER:"
 S FA("ITEMS",6,"LABEL","TOP")=14
 S FA("ITEMS",6,"LABEL","LEFT")=30
 S FA("ITEMS",6,"FIELD","TOP")=14
 S FA("ITEMS",6,"FIELD","LEFT")=40
 S FA("ITEMS",6,"FIELD","MAXLENGTH")=30
 S FA("ITEMS",6,"FIELD","REQUIRED")=1
 S FA("ITEMS",6,"FIELD","ONFOCUS")="S I=$$CHOOSE^TTCUST(.B)"
 S FA("ITEMS",7,"NAME")="POSTDATE"
 S FA("ITEMS",7,"LABEL")="A/R POST DATE:"
 S FA("ITEMS",7,"LABEL","TOP")=16
 S FA("ITEMS",7,"LABEL","LEFT")=25
 S FA("ITEMS",7,"FIELD","TOP")=16
 S FA("ITEMS",7,"FIELD","LEFT")=40
 S FA("ITEMS",7,"FIELD","MAXLENGTH")=10
 S FA("ITEMS",7,"FIELD","REQUIRED")=1
 S FA("ITEMS",7,"FIELD","ONFOCUS")="D CHOOSE^TTDATE($ZDATE($H),""CHOOSE A/R POST DATE"")"
 D GO^TTFORM(.FA)
 G:CANFLG=1 CANCELRECEIVE
 N DATE,CHKNUM,MEMO,CUSTCODE,AMOUNT,NMGRTAMOUNT
 S CUSTCODE=$$GETINTVAL^TTFORM(.FA,"CUSTOMER")
 S DATE=$$GETINTVAL^TTFORM(.FA,"PMTDATE")
 S CHKNUM=$$GETEXTVAL^TTFORM(.FA,"CHKNO")
 S MEMO=$$GETEXTVAL^TTFORM(.FA,"MEMO")
 S AMOUNT=$$GETEXTVAL^TTFORM(.FA,"AMOUNT") 
 S NMGRTAMOUNT=$$GETEXTVAL^TTFORM(.FA,"NMGRT")
 S PMTIDX=^TT("COMPANY","PMTIDX")
 S ^TT("CUSTOMER",CUSTCODE,"PAYMENTS",PMTIDX,"DATE")=DATE
 S ^TT("CUSTOMER",CUSTCODE,"PAYMENTS",PMTIDX,"CHKNUM")=CHKNUM
 S ^TT("CUSTOMER",CUSTCODE,"PAYMENTS",PMTIDX,"MEMO")=MEMO
 S ^TT("CUSTOMER",CUSTCODE,"PAYMENTS",PMTIDX,"AMOUNT")=AMOUNT
 S ^TT("CUSTOMER",CUSTCODE,"PAYMENTS",PMTIDX,"NMGRTAMOUNT")=NMGRTAMOUNT
 S ^TT("COMPANY","PMTIDX")=PMTIDX+1
 I ^TT("CUSTOMER",CUSTCODE,"ACCTINTEG")="TRUE" D
 . N ACCTPER,DEBACCT,CREDACCT,POSTDATE,JOURNAL,POSTAMT
 . S POSTDATE=$$GETINTVAL^TTFORM(.FA,"POSTDATE")
 . S ACCTPER=$$CHOOSEPERIOD^TTACCOUNT
 . S DEBACCT=^TT("CUSTOMER",CUSTCODE,"PMTDEB")
 . S CREDACCT=^TT("CUSTOMER",CUSTCODE,"PMTCRED")
 . S JOURNAL=^TT("CUSTOMER",CUSTCODE)_" PAYMENT "_PMTIDX
 . S POSTAMT=AMOUNT
 . D POST^TTACCOUNT(POSTDATE,POSTAMT,CREDACCT,DEBACCT,ACCTPER,JOURNAL,CHKNUM)
 N PMSG
 S PMSG="Payment of $"_AMOUNT_" posted for "_$$GETEXTVAL^TTFORM(.FA,"CUSTOMER")_"."
 D MSGBOX^TTUI(PMSG,0,"INVOICING")
CANCELRECEIVE
 D:CANFLG=1 MSGBOX^TTUI("Payment canceled.",0,"INVOICING")
 Q