TTSETUP
 W !,"RESPOND COMPANY NAME "
 R ^TT("COMPANY","NAME")
 W !,"RESPOND COMPANY STREET ADDRESS "
 R ^TT("COMPANY","STREET")
 W !,"RESPOND COMPANY CITY "
 R ^TT("COMPANY","CITY")
 W !,"RESPOND COMPANY STATE "
 R ^TT("COMPANY","STATE")
 W !,"RESPOND COMPANY POSTAL CODE "
 R ^TT("COMPANY","ZIP")
 W !,"RESPOND FIRST INVOICE NUMBER "
 R ^TT("COMPANY","INVIDX")
 W !,"RESPOND PHONE NUMBER "
 R ^TT("COMPANY","PHONE")
 W !,"RESPOND FAX NUMBER "
 R ^TT("COMPANY","FAX")
 W !,"RESPOND URL "
 R ^TT("COMPANY","URL")
 W !,"RESPOND CONTACT EMAIL "
 R ^TT("COMPANY","EMAIL")
 S ^TT("COMPANY","LOGIDX")=1
 S ^TT("COMPANY","PMTIDX")=100
 D SETUP^TTACCOUNT
 Q