TTUI
 Q

;
; BA STRUCTURE
;
;  BA("TOP")=n
;  BA("LEFT")=n
;  BA("RIGHT")=n
;  BA("BOTTOM")=n
;  BA("TITLE")="text"
;  BA("LINES",n)="text"
ALERTBOX(BA)
 S BA("SCALEWIDTH")=BA("RIGHT")-BA("LEFT")-2
 S BA("SCALEHEIGHT")=BA("BOTTOM")-BA("TOP")-4
 S BA("CONTENTTOP")=BA("TOP")+3
 S BA("CONTENTLEFT")=BA("LEFT")+1
 S BA("CAPTIONTOP")=BA("TOP")+1
 S BA("CAPTIONLEFT")=BA("LEFT")+1
 D SETCOLOR^TTRNSI("GREEN","BLACK")
 D LOCATE^TTRNSI(BA("TOP"),BA("LEFT"))
 W BOX("UL")
 F I=BA("LEFT")+1:1:BA("RIGHT")-1  D
 . D LOCATE^TTRNSI(BA("TOP"),I) W BOX("H")
 W BOX("UR")
 D LOCATE^TTRNSI(BA("TOP")+1,BA("LEFT")) W BOX("V")
 D LOCATE^TTRNSI(BA("TOP")+1,BA("RIGHT")) W BOX("V")
 D LOCATE^TTRNSI(BA("TOP")+2,BA("LEFT")) W BOX("LT")
 D LOCATE^TTRNSI(BA("TOP")+2,BA("RIGHT")) W BOX("RT")
 F I=BA("LEFT")+1:1:BA("RIGHT")-1  D
 . D LOCATE^TTRNSI(BA("TOP")+2,I) W BOX("H")
 D LOCATE^TTRNSI(BA("BOTTOM"),BA("LEFT")) W BOX("LL")
 D LOCATE^TTRNSI(BA("BOTTOM"),BA("RIGHT")) W BOX("LR")
 F I=BA("LEFT")+1:1:BA("RIGHT")-1  D
 . D LOCATE^TTRNSI(BA("BOTTOM"),I) W BOX("H")
 F ROW=BA("TOP")+3:1:BA("BOTTOM")-1  D
 . D LOCATE^TTRNSI(ROW,BA("LEFT")) W BOX("V")
 . D LOCATE^TTRNSI(ROW,BA("RIGHT")) W BOX("V")
 D LOCATE^TTRNSI(BA("CAPTIONTOP"),BA("CAPTIONLEFT"))
 D SETATTR^TTRNSI("REVERSE")
 F I=BA("CAPTIONLEFT"):1:BA("RIGHT")-1  D
 . D LOCATE^TTRNSI(BA("CAPTIONTOP"),I) W " "
 D LOCATE^TTRNSI(BA("CAPTIONTOP"),BA("CAPTIONLEFT")) W BA("TITLE")
 D SETATTR^TTRNSI("RESET"),SETCOLOR^TTRNSI("GREEN","BLACK")
 N LINE S LINE=""
 F  S LINE=$O(BA("LINES",LINE))
 D HOME^TTRNSI
 Q

CAPTION(CAPTEXT)
 N CAPLEFT
 S CAPLEFT=(80/2)-($L(CAPTEXT)/2)
 S CAPLEFT=$P(CAPLEFT,".",1)
 D LOCATE^TTRNSI(1,CAPLEFT)
 D SETCOLOR^TTRNSI("WHITE","BLACK"),SETATTR^TTRNSI("BRIGHT")
 W CAPTEXT
 D SETATTR^TTRNSI("RESET")
 Q