TTUI
 Q

CAPTION(CAPTEXT)
 N CAPLEFT
 S CAPLEFT=(80/2)-($L(CAPTEXT)/2)
 S CAPLEFT=$P(CAPLEFT,".",1)
 D LOCATE^TTRNSI(1,CAPLEFT)
 D SETCOLOR^TTRNSI("WHITE","BLACK"),SETATTR^TTRNSI("BRIGHT")
 W CAPTEXT
 D SETATTR^TTRNSI("RESET")
 Q